name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    needs: [create_release]
    steps:
      - uses: actions/checkout@v3
      - uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: 'dist/linux/main'
      
