name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-job:
    name: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .
      - uses: actions/upload-artifact@v2
        with:
          name: build-linux
          path: dist/linux
      
