name: publish_windows_binary
run-name: ${{ github.actor }} is publishing windows binary
on:
  release:
    types: [created]
jobs:
  windows-build-job:
    name: windows-build-job
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
      - uses: actions/upload-artifact@v2
        with:
          name: build-windows
          path: dist/
  publish-mac:
    name: publish-windows
    runs-on: ubuntu-latest
    needs: windows-build-job
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-windows
          path: .
      - run: ls -a .
      - run: ls -a *
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r main-mac.zip main
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'main-windows.zip'