name: publish_binary
run-name: ${{ github.actor }} is publishing binary
on:
  release:
    types: [created]
jobs:
  mac-build-job:
    name: mac-build-job
    runs-on: macos-12
    steps:
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - run: pip install pyinstaller
      - run: pyinsatller src/main.py
      - run: ls -a 
      - run: ls -a * 
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: build-mac
      #     path: dist/
  # publish:
  #   name: publish
  #   runs-on: macos-latest
  #   needs: mac-build-job
  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: build-mac
  #         path: .
  #     - uses: montudor/action-zip@v1
  #       with:
  #         args: zip -qq -r main-linux.zip main
  #     - name: Upload the artifacts
  #       uses: skx/github-action-publish-binaries@release-1.3
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         args: 'main-linux.zip'