name: publish_mac_binary
run-name: ${{ github.actor }} is publishing mac binary
on:
  release:
    types: [created]
jobs:
  mac-build-job:
    name: mac-build-job
    runs-on: macos-12
    steps:
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: python -m pytest
      - run: pip install pyinstaller
      - run: pyinstaller src/main.py
      - uses: actions/upload-artifact@v2
        with:
          name: build-mac
          path: dist
  publish-mac:
    name: publish-mac
    runs-on: ubuntu-latest
    needs: mac-build-job
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-mac
          path: .
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r main-mac.zip dist
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'main-mac.zip'